zookeeper:
  hosts:
    zk[1:3].nikoleta.aws.ps.confluent.io:
     
kafka_broker:
  hosts:
    kfk[1:3].nikoleta.aws.ps.confluent.io:
    
control_center:
  hosts:
    ccc1.nikoleta.aws.ps.confluent.io:
       
schema_registry:
  hosts:
    sr[1:2].nikoleta.aws.ps.confluent.io:
                  
kafka_connect:
  hosts:
    connect[1:2].nikoleta.aws.ps.confluent.io:
  vars:
    # Install Connectors from Confluent Hub
    #
    kafka_connect_confluent_hub_plugins_dest: /usr/share/java #Optional variable for controling where they get installed
    kafka_connect_confluent_hub_plugins: #List of Hub Coordinates of where to install to
    - jcustenborder/kafka-connect-spooldir:2.0.43
    #
    # Install a Connector from a local SCP'd file
    #  or from a remote HTTP(S) download
    #kafka_connect_plugins_dest: /usr/share/java #Optional variable for controling where they get installed
    #kafka_connect_plugins:
    #- local/path/to/connect_archive.zip
    #kafka_connect_plugins_remote:
    #- http://myhost.com/connect_archive.zip
                      
ksql:
  hosts:
    ksql1.nikoleta.aws.ps.confluent.io:
      
kafka_rest:
  hosts:
    rest1.nikoleta.aws.ps.confluent.io:
