---
- name: KSQL Status Finding
  hosts: ksql
  gather_facts: false
  tags: ksql
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: confluent.variables

    - name: Check if Kafka Service Running
      shell: "systemctl show -p SubState {{ksql_service_name}}"
      changed_when: false
      # On some SELinux enabled hosts this command will error out, handled in next set_fact task
      failed_when: false
      check_mode: false
      register: substate

    - set_fact:
        install_pattern: "{{ 'parallel' if substate.stdout != 'SubState=running' or substate.rc == 1 or ksql_deployment_strategy == 'parallel' else 'serial' }}"

    - name: "Group Hosts by Installation Pattern: Parallel or Serial"
      group_by:
        key: ksql_{{install_pattern}}

- name: KSQL Parallel Provisioning
  hosts: ksql_parallel
  gather_facts: false
  tags: ksql
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: confluent.ksql

- name: KSQL Serial Provisioning
  hosts: ksql_serial
  serial: 1
  gather_facts: false
  tags: ksql
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: confluent.ksql

    - name: Proceed Prompt
      pause:
        prompt: "Press Enter to Proceed to Next Node. Ctrl + C to Abort"
      when: ksql_pause_rolling_deployment|bool
