---
- name: Control Center Upgrade
  hosts: control_center
  gather_facts: false
  environment: "{{ proxy_env }}"
  serial: 1
  tasks:
    - name: Gather OS Facts
      setup:
        # Only gathers items in list, filters out the rest
        filter: ansible_os_family
        gather_subset:
          - '!all'

    - import_role:
        name: confluent.variables

    - name: Get Package Facts
      package_facts:
        manager: auto
      when: installation_method == "package"

    - name: Set control_center_current_version variable - Package
      set_fact:
        confluent_server_enabled: "{{ True if ansible_facts.packages['confluent-server'] is defined else False }}"
        control_center_current_version: "{{ ansible_facts.packages['confluent-control-center'][0]['version'] }}"
      when: installation_method == "package"

    - name: Load override.conf
      slurp:
        src: "{{ control_center.systemd_override }}"
      register: slurped_override
      when: installation_method == "archive"

    - name: Set control_center_current_version variable - Archive
      set_fact:
        control_center_current_version: "{{ (slurped_override.content|b64decode) .split('\n') |
          select('match', '^ExecStart=' + archive_config_base_path + '/confluent-(.*)/bin/control-center-start ' + control_center.config_file) |
          list | first | regex_search('[0-9]+(.[0-9]+)+') }}"
      when: installation_method == "archive"

    - debug:
        msg: "Current version: {{control_center_current_version}}   Upgrade to version: {{confluent_package_version}}"

    - name: Upgrade Control Center - Package
      include_tasks: tasks/upgrade_component.yml
      vars:
        service_name: "{{ control_center_service_name }}"
        packages: "{{ control_center_packages }}"
        backup_files:
          - "{{ control_center.config_file }}"
          - "{{ control_center.systemd_override }}"
        restore_files:
          - "{{ control_center.config_file }}"
      when:
        - control_center_current_version != confluent_full_package_version
        - control_center_current_version != confluent_package_version
        - installation_method == "package"

    - name: Upgrade Control Center - Archive
      include_tasks: tasks/upgrade_component_archive.yml
      vars:
        service_name: "{{ control_center_service_name }}"
        systemd_file: "{{ control_center.systemd_file }}"
        systemd_override: "{{ control_center.systemd_override }}"
        start_script: "control-center-start"
        config_file: "{{ control_center.config_file }}"
      when:
        - control_center_current_version != confluent_full_package_version
        - control_center_current_version != confluent_package_version
        - installation_method == "archive"

    - name: Control Center Health Check
      import_role:
        name: confluent.control_center
        tasks_from: health_check.yml
      when: not ansible_check_mode
