---
- name: Host Prerequisites
  hosts: zookeeper:kafka_broker:schema_registry:kafka_connect:ksql:control_center:kafka_rest
  tags:
    - preflight
  tasks:
  - import_role:
      name: confluent.common

- name: Zookeeper Provisioning
  hosts: zookeeper
  tags:
    - zookeeper
  tasks:
  - import_role:
      name: confluent.zookeeper
#    vars:
#      zookeeper_packages:
#        - "confluent-common-{{confluent_full_package_version}}"
#        - "confluent-kafka-2.12-2.2.2-cp1-1"

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  tags:
    - kafka_broker
  tasks:
  - import_role:
      name: confluent.kafka_broker
#    vars:
#      kafka_broker_packages:
#        - "confluent-common-{{confluent_full_package_version}}"
#        - "confluent-kafka-2.12-2.2.2-cp1-1"
#        - "confluent-rebalancer-{{confluent_full_package_version}}"
#        - "confluent-security-{{confluent_full_package_version}}"

- name: Schema Registry Provisioning
  hosts: schema_registry
  tags:
    - schema_registry
  tasks:
  - import_role:
      name: confluent.schema_registry
#    vars:
#      schema_registry_packages:
#        - "confluent-common-{{confluent_full_package_version}}"
#        - "confluent-kafka-2.12-2.2.2-cp1-1"
#        - "confluent-rest-utils-{{confluent_full_package_version}}"
#        - "confluent-schema-registry-{{confluent_full_package_version}}"
#        - "confluent-security-{{confluent_full_package_version}}"

- name: Kafta Connect Provisioning
  hosts: kafka_connect
  tags:
    - kafka_connect
  tasks:
  - import_role:
      name: confluent.kafka_connect
#    vars:
#      kafka_connect_packages:
#        - "confluent-common-{{confluent_full_package_version}}"
#        - "confluent-kafka-2.12-2.2.2-cp1-1"
#        - "confluent-kafka-connect-storage-common-{{confluent_full_package_version}}"
#        - "confluent-kafka-connect-s3-{{confluent_full_package_version}}"
#        - "confluent-kafka-connect-elasticsearch-{{confluent_full_package_version}}"
#        - "confluent-kafka-connect-jdbc-{{confluent_full_package_version}}"
#        - "confluent-kafka-connect-jms-{{confluent_full_package_version}}"
#        - "confluent-kafka-connect-replicator-{{confluent_full_package_version}}"
#        - "confluent-rest-utils-{{confluent_full_package_version}}"
#        - "confluent-security-{{confluent_full_package_version}}"
#        - "confluent-control-center-fe-{{confluent_full_package_version}}"
#        - "confluent-control-center-{{confluent_full_package_version}}"
#        - "confluent-schema-registry-{{confluent_full_package_version}}"

- name: KSQL Provisioning
  hosts: ksql
  tags:
    - ksql
  tasks:
  - import_role:
      name: confluent.ksql

- name: Kafka Rest Provisioning
  hosts: kafka_rest
  tags:
    - kafka_rest
  tasks:
  - import_role:
      name: confluent.kafka_rest

- name: Control Center Provisioning
  hosts: control_center
  tags:
    - control_center
  tasks:
  - import_role:
      name: confluent.control_center
#    vars:
#      control_center_packages:
#        - "confluent-common-{{confluent_full_package_version}}"
#        - "confluent-kafka-2.12-2.2.2-cp1-1"
#        - "confluent-rest-utils-{{confluent_full_package_version}}"
#        - "confluent-control-center-fe-{{confluent_full_package_version}}"
#        - "confluent-control-center-{{confluent_full_package_version}}"
