- hosts: preflight
  become: yes
  pre_tasks:
  - name: create ssl certificate directory
    file:
       path: /var/ssl/private
       state: directory
       mode: 0755
  - name: copy ssl related files to host
    synchronize:
       src: generated_ssl_files/
       dest: /var/ssl/private
       rsync_opts:
       - "--include={{inventory_hostname}}.jks"
       - "--delete"
  - name: create keytab certificate directory
    file:
       path: /etc/security/keytabs
       state: directory
       mode: 0755
  - name: copy keytab related files to host
    copy:
       src: "keytabs/{{inventory_hostname}}.keytab"
       dest: "/etc/security/keytabs/{{inventory_hostname}}.keytab"
       mode: '644'
  - name: Install the Kerberos Deps
    apt:
       name: 
       - realmd 
       - krb5-user 
       - samba-common
       - packagekit
       - adcli #RHEL sssd realmd krb5-workstation samba-common-tools
       update_cache: yes
  tasks:
  - import_role:
      name: confluent.preflight
    become: yes
    
    
    
- hosts: zookeeper
  become: yes
  pre_tasks:
#  - name: Zookeeper JAAS File
#    template:
#       src: krb5.jaas.j2
#       dest: "/etc/kafka/zookeeper_jaas.conf"
#       mode: 0640
#    vars:
#       name: Client
#       keytab_file: "{{inventory_hostname}}.keytab"
#       spn: "{{host_spn}}"
          
  tasks:
  - import_role:
      name: confluent.zookeeper
      
      
      
- hosts: broker
  become: yes
  pre_tasks:
  - name: Broker JAAS File
    template:
       src: krb5.jaas.j2
       dest: "/etc/kafka/kafka_jaas.conf"
       mode: 0640
    vars:
       name: KafkaServer
       keytab_file: "{{inventory_hostname}}.keytab"
       spn: "{{host_spn}}"
     
  tasks:
  - import_role:
      name: confluent.kafka-broker
      
      
- hosts: control-center
  become: yes
     
  tasks:
  - import_role:
      name: confluent.control-center